project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://IsabellaHannaCSM.github.io
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/IsabellaHannaCSM
format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css



